Repository ArkEcosystem/php-crypto, pull requests merged in 2019-05, with the labels that each got.

#41 chore: update contribution link
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#42 feat: support new vendorfield length
  src/Transactions/Transaction.php
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#44 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#45 chore: add itsanametoo to code owners
  CODEOWNERS
Labels: Complexity: Low, Type: Task
