Repository ArkEcosystem/php-crypto, pull requests merged in 2020-10, with the labels that each got.

#101 fix: support signatory alias for message public key
  src/Utils/Message.php
Labels: Complexity: Low, Type: Bugfix

#103 chore: use Pest to run tests
  .github/workflows/test.yml
  .gitignore
  composer.json
  tests/Helpers.php
  tests/Pest.php
Labels: Complexity: Low, Type: Task

#105 fix: return type of the new method
  src/Utils/Message.php
Labels: bugfix, low
