Repository ArkEcosystem/php-crypto, pull requests merged in 2020-01, with the labels that each got.

#80 Apply fixes from StyleCI
  src/Transactions/Builder/MultiPaymentBuilder.php
  src/Transactions/Types/MultiPayment.php
Labels: Complexity: Low

#81 fix: enable vendorfield for multipayment
  src/Transactions/Builder/MultiPaymentBuilder.php
  src/Transactions/Types/MultiPayment.php
  tests/Transactions/Builder/MultiPaymentTest.php
Labels: Complexity: Low, Type: Bugfix

#86 ci: replace StyleCI with GitHub Workflows
  .github/workflows/format.yml
  .php_cs
  .styleci.yml
Labels: Complexity: High
